[tool.black]
line-length = 120
skip-string-normalization = true
force-exclude = "/fixtures.py"

[tool.pytest.ini_options]
mock_use_standalone_module = true

[tool.isort]
line_length = 120
multi_line_output = 3
indent = 4
